# include<stdio.h>

/* int main (void) //void indicates thst no arguments in the paranthesis
{
     printf ("Programming is fun.\n");
     printf("C prog is more fun");
     return 0; //semicolon to terminate
} */

/*int main(void)
{
     printf("loading...\n..1\n...2\n....3\n");
     printf("check");
     return 0;
}*/

/*int main(void)
{
     int sum; //initiate variable
     sum = 50 + 25; //define variable
     printf("the sum of 50 and 25 is %i\n",sum); //i indicates the output is an integer
     return 0;
}*/


/*int main(void)
{
     int num1, num2, sum; //declaration of variables
     num1 = 10;
     num2 = 20;
     sum = num1+num2;
     printf("the sum of %i and %i is %i\n",num1,num2,sum); // similar to old style formatting
     return 0;
}*/

/*int main (Void)
{
        int  sum;
        // COMPUTE RESULT
        sum = 25 + 37 - 19;
        //DISPLAY RESULTS 
        printf ("The answer is %i\n", sum);
        return 0;
}**/

/*int main (void)
{
      int answer, result;

      answer = 100;
      result = answer - 10;
      printf ("The result is %i\n", result + 5);

      return 0;
}*/

// printf ("Color is %#x\n", rgbColor);


/*int main (void)
{
     int       integerVar = 100;
     float     floatingVar = 331.79;
     double    doubleVar = 8.44e+11;
     char      charVar = 'W';

     _Bool     boolVar = 0;

     printf ("integerVar = %i\n", integerVar);
     printf ("floatingVar = %f\n", floatingVar);
     printf ("doubleVar = %e\n", doubleVar);
     printf ("doubleVar = %g\n", doubleVar);
     printf ("charVar = %c\n", charVar);

     printf ("boolVar = %i\n", boolVar);

     return 0;
}*/

// Program to calculate the 200th triangular number. Introduction of the for statement

/*int main(void)
{
     int n, trinum;

     trinum = 0;
     for (n=1; n<=200; n = n+1)
          trinum +=n;
     printf("the %ith triangular number is %i\n",n-1,trinum);
     return 0;
}*/

// Program to generate a table of triangular numbers

/*int main(void)
{
     int n, trinum;

     printf("table of triangular numbers\n");
     printf("num    sum from 1 to n\n");

     trinum = 0;
     for (n=1;n<=10;++n)
     {
          trinum += n;
          printf("%i     %i\n",n,trinum);
     }
     return 0;
}*/

/*int main(void)
{
     int n, trinum;

     printf("table of triangular numbers\n");
     printf("num    sum from 1 to n\n");

     trinum = 0;
     for (n=1;n<=10;++n)
     {
          trinum += n;
          printf("%2i     %i\n",n,trinum);
     }
     return 0;
}*/

/*int main(void)
{
     int n, num, trinum;

     printf("what triangular number do you want?");
     scanf("%i",&num);

     trinum = 0;

     for (n=1; n <= num; ++n)
          trinum += n;
     
     printf("triangular number %i is %i\n",num,trinum);

     return 0;
}*/

/*int main(void)
{
     int n,num,trinum,counter;

     for (counter =1; counter <= 5; ++counter)
     {
          printf("what triangular number do you want?");
          scanf("%i",&num);

          trinum = 0;

          for (n=1; n <= num; ++n)
               trinum+=n;
          
          printf("triangular number %i is %i\n",num,trinum);
     }

     return 0;
}*/

/*int main(void)
{
     int count = 1;

     while (count<=5)
     {
          printf("%i\n",count);
          ++count;
     }
     
     return 0;
}*/

//Program to find the greatest common divisor of two nonnegative integer values

/*int main(void)
{
     int u,v,temp;

     printf("enter two nonnegative integers:\n");
     scanf("%i%i",&u,&v);

     while (v !=0)
     {
          temp = u%v;
          u=v;
          v=temp;
     }

     printf("the greatest common divisor is %i\n",u);

     return 0;
}*/


//program to reverse an entered number
/*int main(void)
{
     int num,rev_num;

     printf("enter the nuber to be reversed:");
     scanf("%i",&num);

     while (num != 0)
     {
          rev_num= num %10;
          printf("%i",rev_num);
          num/=10;
     }
     printf(" is the reveresed number");
     return 0;
}*/

/*int main ()
{
     int  number, right_digit;

     printf ("Enter your number.\n");
     scanf ("%i", &number);

     do {
         right_digit = number % 10;
         printf ("%i", right_digit);
         number = number / 10;
     }
     while ( number != 0 );

     printf ("\n");

     return 0;
}*/

/*int main (void)
{
   int  dollars, cents, count;

   for ( count = 1;  count <= 10;  ++count ) {
        printf ("Enter dollars: ");
        scanf ("%i", &dollars);
        printf ("Enter cents: ");
        scanf ("%i", &cents);
        printf ("$%i.%.2i\n\n", dollars, cents);
   }
   return 0;
}*/

//1. Write a program to generate and display a table of n and n2, for integer values of n ranging from 1 to 10. Be certain to print appropriate column headings.

/*int main(void)
{
     int n;

     printf("n     n2\n");
     for (n=1; n<=10; ++n)
          printf("%2i    %i\n",n,n*n);
     return 0;
}*/

/*2. A triangular number can also be generated by the formula: triangularNumber = n (n + 1) / 2
for any integer value of n. For example, the 10th triangular number, 55, can be generated by 
substituting 10 as the value for n in the preceding formula. Write a program that generates a 
table of triangular numbers using the preceding formula. Have the program generate every fifth 
triangular number between 5 and 50 (that is, 5, 10, 15, ..., 50).*/

/*3. The factorial of an integer n, written n!, is the product of the consecutive integers 1 through n. For example, 5 factorial is calculated as
5!  =  5 x 4 x 3 x 2 x 1  =  120. Write a program to generate and print a table of the first 10 factorials.*/

/*4. The following perfectly valid C program was written without much attention paid to its format.
As you will observe, the program is not very readable. (And believe it or not, it is even possible
to make this program significantly more unreadable!) Using the programs presented in this chapter
as examples, reformat the program so that it is more readable. Then type the program into the computer and run it.

#include <stdio.h>
int main(void){
int n,two_to_the_n;
printf("TABLE OF POWERS OF TWO\n\n");
printf(" n     2 to the n\n");
printf("---    ---------------\n");
two_to_the_n=1;
for(n=0;n<=10;++n){
printf("%2i        %i\n",n,two_to_the_n); two_to_the_n*=2;}
return 0;}*/

/*5. Modify that program of the triangu  ar numbers so that the user can type in the number of triangular numbers to be calculated.*/

/*6. Write a program that calculates the sum of the digits of an integer. 
For example, the sum of the digits of the number 2155 is 2 + 1 + 5 + 5 or 13.
The program should accept any arbitrary integer typed in by the user.*/